name: Main Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform-deployment:
    uses: ./.github/workflows/terraform-deployment.yml  
    with:
      terraform_version: '1.10.3'
      tf_backend_config: './config/backend.tf'  
      tf_vars: './config/terraform.tfvars'  
    secrets: inherit
