name: Terraform Deployment

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'Terraform version to use'
        required: true
        default: '1.5.0'
        type: string
      tf_backend_config:
        description: 'Path to Terraform backend config file'
        required: false
        default: './backend.tf'
        type: string
      tf_vars:
        description: 'Path to Terraform variables file'
        required: false
        default: './terraform.tfvars'
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false  

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: |
          terraform init -backend-config="${{ inputs.tf_backend_config }}"

      - name: Terraform Plan
        run: |
          terraform plan -var-file="${{ inputs.tf_vars }}"

      - name: Terraform Apply
        if: ${{ github.event_name == 'push' }}  # Only apply on push events
        run: |
          terraform apply -auto-approve -var-file="${{ inputs.tf_vars }}"
